### ISSUE TITLE
Data cleaning & organizing the dataset

### ISSUE THREAD

**Issue by teddywaweru** [teddywaweru/2110ACDS_ND5#11]
- [x] Organize the data by getting rid of null values & outliers
- [x] Discard unnecessary columns
- [x] Create new columns as necessary ie. time series
- [x] Arrange columns systematically

**Comment by McMunashe** [comment]
Working on the time series column. Thinking of creating a year column will see how it goes.

**Comment by teddywaweru** [comment]
I shall close this issue since i don't think there's any pending task to it.
