### ISSUE TITLE
Data cleaning, categorization & analysis based on Cities

### ISSUE THREAD

**Issue by teddywaweru** [teddywaweru/2110ACDS_ND5#6]
To cover on the following:
- [ ] Data Cleaning
- [ ] Data Categorization based on weather attributes
- [x] Exploratory Analysis

**Comment by McMunashe** [comment]
There is a lot of copy and paste if we categorize by cities.

**Comment by teddywaweru** [comment]
Noted. I'll close this since it is no longer relevant in our strategy.
